import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import '@/common/styles/globals.scss';
import 'react-loading-skeleton/dist/skeleton.css';
import 'simplebar-react/dist/simplebar.min.css';

import Provider from '@/common/components/poviders/Provider';
import { Toaster } from '@/common/components/ui/sonner';
import { cn } from '@/common/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'PenPal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('min-h-screen font-sans antialiased', fontSans.variable)}
      >
        <Provider>
          <Toaster />
          {children}
        </Provider>
      </body>
    </html>
  );
}
