import type { Metadata } from 'next';

import '@/common/styles/globals.scss';

export const metadata: Metadata = {
  title: 'PenPal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
